name: ichazy
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.5
  dio: ^3.0.10
  file_picker: '2.0.6'
  image_cropper: ^1.3.1
  camera_camera: ^1.0.34+1
  json_serializable: ^3.5.0
  flutter_cache_manager: ^2.0.0
  url_launcher: ^5.7.2
  shared_preferences: ^0.5.12+4
  flushbar: ^1.10.4
  path_provider: ^1.6.24
  path: ^1.7.0
  flutter_image_compress: ^0.7.0
  flutter_launcher_icons: ^0.8.1
  route_observer_mixin: ^1.4.2+2
  barcode: ^1.17.1
  barcode_widget: ^1.5.0
  fijkplayer: ^0.8.7
  flutter_ffmpeg: ^0.3.0

flutter_icons:
  image_path: 'assets/icons/png/app_icon.png'
  android: true
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/icons/wo bg/
    - assets/icons/png/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: SF
      fonts:
        - asset: assets/fonts/SF-UI-Display-Light.ttf
          weight: 300
        - asset: assets/fonts/SF-UI-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-UI-Display-Medium.ttf
          weight: 500
        - asset: assets/fonts/SF-UI-Display-Semibold.ttf
          weight: 600
